### PR TITLE
Configure Travis to run htmlproofer on PRs

### PR DESCRIPTION
**Pull request by jouvin**
`htmlproofer` is a Ruby module to check consistency of a web site. In particular it detects incorrect construct and dead link. It seems important to run it to ensure the quality of our website.

Once the PR has been merged, if you want to check on your machine that `htmlproofer`validates your changes, you need to execute:
```
./travis-build
```
But you can just wait for Travis to run it after you pushed something...

This PR is a second attempt, after the closed #56. It disabled checks of external links (too many failings): this is may be something to review in the future.

This PR is ready for merging (as sson as tests are ok!) but may require rebasing after #74 is merged (I suggest merging #74 first as it is probably easier and less urgent to rebase this one)...

### CODE REVIEW

**Comment by jouvin** [comment]
Rebased on last modifications (activities, GSoC...). But GSoC pages have a few problems, I'll try to fix them asap...

**Comment by hegner** [comment]
@jouvin - working on the GSoC right now and reorganizing. The last PR by Omar you merged was wrong. Please wait w/ your cleanup once done.

**Comment by jouvin** [comment]
Ok, sorry for missing what was wrong... I'll rebase on your coming fix and it should be ok!

**Comment by hegner** [comment]
@jouvin - please go on

**Comment by jouvin** [comment]
@hegner unfortunately, it makes no sense to go on until #81 (I should have open an issue...) is fixed and merged as it is the cause of the error.

**Pull request merged**
