### PR TITLE
Update get_involved.md

### PR DESCRIPTION
**Pull request by gaede**

### CODE REVIEW

**Comment by hegner** [comment]
@gaede - can you resolve the conflicts? Thanks!

**Comment by jouvin** [comment]
@gaede if it helps, the problem is that you modified a version of the file that has been updated since. You need to fetch the last version of `hep-sf/master` and `git rebase` your branch on it (and fix the conflict).

**Comment by gaede** [comment]
I have committed the changes directly to the hep-sf/master - close pull request.

**Comment by jouvin** [comment]
@gaede this is particularly a bad practice, in particular if your pull request had a conflict... There is a high risk of doing something wrong!

**Comment by gaede** [comment]
This has happened somewhat accidentally as I had fixed the conflict locally in my working directory (working with two remotes) and then pushing it
to the wrong remote - not being aware that I had write access to this as well.  Still learning git. 
Anyways - looking at the diff I am pretty sure that I have not broken anything but committed my intended fix of providing a ling to the hsf google group...
> On 13 May 2016, at 21:26, Michel Jouvin <notifications@github.com> wrote:
> 
> @gaede this is particularly a bad practice, in particular if your pull request had a conflict... There is a high risk of doing something wrong!
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> 

------------------------------------ 
Dr. Frank Gaede
DESY - FLC
 Phone:  +49 40 8998 4382    
 Fax:    +49 40 8994 4382
 E-mail: frank.gaede@desy.de

**Comment by jouvin** [comment]
I understand, I did the same mistake a significant number of times in other project when I was a Git newbie! And as you said, I don't think it caused anything wrong in this particular case...
If it helps, my trick to avoid this is the following command, anytime I am not sure about the remote used by push by default:
```
git push --set-upstream origin HEAD
```
For this to work you have to ensure that your remote `origin` is your fork and not the `hep-sf` repo (`git remote -v` allows to check it). `--set-upstream` defines the default remote to be used by next push operations to the one used in this one defined as the current branch (`HEAD`) on the remote `origin`.

This reminds me that I have to write a GitLab Survival Kit for AIDA WP3!

**Pull request closed without merging**
