### PR TITLE
Finalize KB newsletter draft.

### PR DESCRIPTION
**Pull request by hegner**

### CODE REVIEW

**Comment by jouvin** [comment]
I'd suggest to decouple both things. We need to remove the link as soon as we make the new site production, better to do it immediately. We may (or may not) need more time to refine the logo contest text...

**Comment by hegner** [comment]
Made a separate request for the logo now.

**Comment by jouvin** [comment]
Now than #10 is merged, you probably to rebase this PR on master.

**Comment by jouvin** [comment]
@hegner I opened a PR on your source branche with some minor mods (https://github.com/hegner/hep-sf.github.io/pull/2).

**Comment by jouvin** [comment]
As for me, I'm happy to merge it. @HEP-SF/startup any objection?

**Comment by hegner** [comment]
Merging now would make it immediately visible.

**Comment by jouvin** [comment]
Merging... We may fix (probably minor) issues found later...

**Pull request merged**
