### PR TITLE
gsoc: add GoHEP project and LPC organization

### PR DESCRIPTION
**Pull request by sbinet**
This CL adds the "LPC Clermont" laboratory (IN2P3) as an organization.

### CODE REVIEW

**Comment by jouvin** [comment]
@sbinet unfortunatly work is still in progress to streamline organization addition. You also need (undocumented!) to edit `_activity/gsoc.md` and add your organization in the list in the relevant section (copy/paste an existing one, add your logo in `images/`).

**Comment by sbinet** [comment]
yep, noticed it.
(done.)

**Comment by jouvin** [comment]
Unfortunately, you need to rebase: `gsoc.md` has a conflict.

**Comment by sbinet** [comment]
done.

**Pull request merged**
