### PR TITLE
add ATLAS Rucio GSOC proposal

### PR DESCRIPTION
**Pull request by mlassnig**
Affiliation:
- Vincent Garonne & Cedric Serfon (University of Oslo)
- Mario Lassnig & Martin Barisits (CERN EP)

### CODE REVIEW

**Comment by hegner** [comment]
@mlassnig - can you resolve the conflicts first?

**Comment by hegner** [comment]
@mlassnig - nevermind. I'll handle that. It's quicker

**Comment by mlassnig** [comment]
Thanks! I just realised that you pushed to my repo as well ;-)

**Comment by hegner** [comment]
@mlassnig - yap. It is a nice but surprising feature.

**Pull request merged**
