### PR TITLE
add CTD/WIT 2017 announcement in events/_posts

### PR DESCRIPTION
**Pull request by dhrou**
add CTD/WIT 2017 announcement in events/_posts (checked running jekyll locally)

### CODE REVIEW

**Comment by dhrou** [comment]
Ping, can this pull request be accepted please ? (or commented)

**Comment by jouvin** [comment]
@dhrou I was about to merge it but for some reason, the event doesn't show up in the list of events on the main page. I'm  trying to figure out what the problem is....

**Comment by jouvin** [comment]
@dhrou I just added the missing file for the announcement to be visible from the home page and I opened a PR on your source branch. Accept it if you agree and this should fix the problem. I'll merge your PR when I get your feedback.

**Comment by dhrou** [comment]
OK I accepted your (Michel) PR  in my github, do I need to do more ?

**Comment by jouvin** [comment]
@dhrou should be ok. Check that the end result matches your expection!

**Pull request merged**
