### PR TITLE
GSoC project page automation

### LINKED ISSUE #110: GSoC: suggested improvements for managing the projects and organizations
Based on the experience during GSoC 2017 project application phase, it would be nice to streamline a little bit more the management of projects and organizations. In particular, it would be nice to be able to add a project or organization without doing anything else than adding its MD page. Currently, it is still necessary to edit the main page to add it to the list. Also organizations have no description on the organization page, conversely to projects. All these flaws could be easily solved if the organizations and projects were turned into Jekyll collections (one for projects, one for organizations. Then it would be very easy to generate the list from the collection with a small Jekyll template (basically a `for` loop over the projects/organizations if we accept to sort them alphabetically).

Main things to be done are:
- [x] Convert projects and organizations to Jekyll collections
- [x] Generate the project/organization list on the main page with a Jekyll template: this includes adding in the project/organization front-matter an `icon` and a `summary` attribute.
- [x] On the organization page, display before the project list either the `description` attribute if present or the `summary`one (mandatory for the main page). Very similar to what is already done for project in `_includes/gsoc_project.ext`.
- [x] To improve readability on mobile devices, turn into an item list the proposal list built in `_includes/gsoc_project.ext` and `_includes/gsoc_proposal.ext` (to be renamed `_includes/gsoc_organization.ext`).

### PR DESCRIPTION
**Pull request by jouvin**
- Projects and organisations list generated from existing ones

Fixes #110

### CODE REVIEW

**Comment by jouvin** [comment]
Still preliminary... just a placeholder to show that it is in progress! Should be complete soon.

**Comment by jouvin** [comment]
Now done with projects... starting with organizations.

**Comment by jouvin** [comment]
Should be complete now. No change to the resulting layout: just the contents of the "index" page is built dynamically.

**Comment by jouvin** [comment]
According to my tests, my mods work. Errors reported by htmlproofer are suspect: it seems we are not using the standard version of jekyll. Could something be wrong with the new collections created? I'll try to look at it tomorrow...

**Comment by jouvin** [comment]
Problem found, it is in the backlink from the proposal to related project and organization due to changed URL. I'm fixing it.

**Comment by jouvin** [comment]
The errors at this point are due to 2017 proposals: their backlink to the related project/organization is no longer working until 2017 is migrated to the new structure. This is not a problem in itself but requires a non-trivial filtering per year in `_activities/gsoc.html` that I'll try to do tomorrow.
Another error is caused by the missing logo for `Spark3D` project. The guidelines related error will disappear when this PR is merged.
I'd suggest to merge this PR as it is because it improves the main page for 2018 which has several missing projects.

**Comment by hegner** [comment]
@jouvin - thanks for this! Not all of the errors reported are for 2017 though. And I would only merge this once 2017 works as well. Just let me know whether you can work on this this morning. If not, I will do the remaining pieces.

**Comment by jouvin** [comment]
I'm working on it. Should be ok soon...

**Comment by hegner** [comment]
Thanks! One more thing to fix and then I will go through it :-)

**Comment by jouvin** [comment]
@hegner it should be ok. Remaining errors are chicken&egg problems in the guidelines (reference to files part of this PR).

There is one minor issue remaining: markdown in project/organization descriptions are improperly parsed... Can be fixed later, not critical IMO. I'm working on it during your review of this PR.

2017 projects and organizations have been migrated to the new structure but the index file has been kept as a static list (rather than the dynamically generated one in 2018) to avoid the need to update the project/organization required front-matter update. Should be harmless as this list has no reason to change.

**Comment by jouvin** [comment]
Last problem mentioned in https://github.com/HEP-SF/hep-sf.github.io/pull/233#issuecomment-361189080 fixed. Ready for merging!

**Pull request merged**
