### PR TITLE
Add another link to newsletter on front page

### PR DESCRIPTION
**Pull request by hegner**
As discussed during the meeting today adding another link to the newsletter.

### CODE REVIEW

**Comment by jouvin** [comment]
@hegner you made something wrong when creating this topical branch. It contains the newsletter draft and it should not... You need to cherry-pick you last commit on a new branch created from upstream/master (or `rebase -i` to remove the two unwanted commits)...
Apart from that I think (at least this is my understanding)  the remark was not that a link was missing but that the concept of subscription was inappropriate. May be change for something like "look at other issues of our newsletter".

**Comment by hegner** [comment]
@jouvin - ops. sorry.

**Comment by jouvin** [comment]
No real need to close the PR! Just do a forced push once you have fixed your branch.

**Comment by hegner** [comment]
@jouvin - no, no. I create a new one w/ clean history.

**Comment by jouvin** [comment]
After the rebase, the history is clean! This is what is great with a rebase!

**Comment by jouvin** [comment]
I remember that it used to be a difference with GitLab (but I think they fixed it now). In GitHub, if you rebase, all the commits previously added are removed from the discussion thread. Thus the result is pretty good.

**Pull request closed without merging**
