### PR TITLE
Create LLR.md

### PR DESCRIPTION
**Pull request by grasseau**
The file LLR-logo.jpg is missing ...

### CODE REVIEW

**Comment by etejedor** [comment]
Could you please complete the PR with the LLR-logo.jpg file? There is a directory called `images` where you can upload it.

**Comment by grasseau** [comment]
Hi, 

I cannot upload under the "images" directory.
I put the logo in this comment but I think that it won't worK
Best regard.
Gilles

llr-logo

**Comment by hegner** [comment]
Uploading just means moving it to the images directory and doing a git add/commit/push

**Comment by hegner** [comment]
Superseded by #265

**Pull request closed without merging**
