### PR TITLE
Added a post about the HSF Visualization Workshop

### PR DESCRIPTION
**Pull request by ric-bianchi**
A new post about the HSF Visualization workshop, as suggested by Torre.

commits have been squashed already

### CODE REVIEW

**Comment by jouvin** [comment]
@ric-bianchi thanks for the summary. Unfortunately, it is not in the right place and thus doesn't show up! We definitely need to improve the documentation about how to contribute to the web site! It should be enough to move it to the `organization/_posts` directory and edit the front-matter to be the same as other meetings in this directory. `events` is a special directory where the things there are shown in the event announcement section until the start_date...

A minor thing that you may want to fix at the same time: I saw in your main visualization page that the links to the agendas at the end are not rendered as link. It would be better to just use the standard markdown syntax for links (as in the following lines):
```
[Agenda](http:...)
```

**Comment by wenaus** [comment]
I suggested that Ric add it to the events page which I take to be a record of past and forthcoming events.

**Comment by ric-bianchi** [comment]
Thanks for your message, Michel, and sorry for the confusion. I will move the page to "posts" later, as you suggested, and I will fix the links. 

Thanks,

   Ric.

---
Sent from my phone.
"I apologize for any mistakes due to typing by cell phone and the help of the Autocorrect tool!"

**Comment by wenaus** [comment]
It should be where it is, not under organization/_posts

**Comment by wenaus** [comment]
I merged it and it appears properly

**Comment by ric-bianchi** [comment]
Thanks for the confirmation, Torre, and for the merge.

I will then fix the links later.

Cheers,

   Ric.

---
Sent from my phone.
"I apologize for any mistakes due to typing by cell phone and the help of the Autocorrect tool!"

**Comment by jouvin** [comment]
@wenaus @ric-bianchi my mistake, it's true that being in events, it just appears in the event page... But it will get a better exposure if you can link it from the visualization page too (and fix the links to the agendas at the same time).

**Pull request merged**
